version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.37.0
    - 1.37.1
    - 1.37.11
    - 1.37.12
    - 1.37.13
    - 1.37.14
    - 1.37.15
    - 1.37.16
    - 1.37.17
    - 1.37.18
    - 1.37.19
    - 1.37.2
    - 1.37.20
    - 1.37.21
    - 1.37.22
    - 1.37.23
    - 1.37.26
    - 1.37.27
    - 1.37.28
    - 1.37.29
    - 1.37.3
    - 1.37.30
    - 1.37.31
    - 1.37.32
    - 1.37.33
    - 1.37.5
    - 1.37.6
    - 1.37.7
    - 1.37.9
    - 1.38.0
    - 1.38.1
    - 1.38.12
    - 1.38.13
    - 1.38.14
    - 1.38.15
    - 1.38.16
    - 1.38.17
    - 1.38.19
    - 1.38.2
    - 1.38.20
    - 1.38.21
    - 1.38.22
    - 1.38.23
    - 1.38.24
    - 1.38.25
    - 1.38.26
    - 1.38.27
    - 1.38.3
    - 1.38.4
    - 1.38.6
    - 1.38.7
    - 1.38.9
  - dependency-name: github.com/chromedp/chromedp
    versions:
    - 0.6.11
    - 0.6.12
    - 0.6.9
  - dependency-name: github.com/microcosm-cc/bluemonday
    versions:
    - 1.0.6
    - 1.0.8
  - dependency-name: github.com/mholt/certmagic
    versions:
    - 0.12.0
    - 0.13.0
  - dependency-name: github.com/webx-top/client
    versions:
    - 0.2.0
    - 0.2.2
  - dependency-name: github.com/admpub/frp
    versions:
    - 0.36.3
  - dependency-name: github.com/webx-top/com
    versions:
    - 0.2.0
  - dependency-name: github.com/admpub/log
    versions:
    - 0.2.1
  - dependency-name: github.com/webx-top/pagination
    versions:
    - 0.0.2
