version: '3'
services:
  nging:
    container_name: nging # 先锋版为 nging-dockermgr
    image: admpub/nging:latest # 先锋版为 admpub/nging-dockermgr:latest
    depends_on:
      - mysql
    expose:
      - 9999
      - 80
      - 443
    ports:
      - 9999:9999
      - 80:80
      - 443:443
    links:
      - "mysql:mysql"
    volumes:
      - ./nging-data/nging/data/cache:/home/nging/data/cache
      - ./nging-data/nging/data/ftpdir:/home/nging/data/ftpdir
      - ./nging-data/nging/data/logs:/home/nging/data/logs
      - ./nging-data/nging/data/sm2:/home/nging/data/sm2
      - ./nging-data/nging/myconfig:/home/nging/myconfig
      - ./nging-data/nging/public:/home/nging/public
      #- /var/run/docker.sock:/var/run/docker.sock  # 先锋版按需配置
      #- /etc/docker/daemon.json:/etc/docker/daemon.json  # 先锋版按需配置
    command: [ "-p", "9999", "-c", "myconfig/config.yaml" ]
    restart: always
  mysql:
    container_name: nging-mysql
    image: mysql
    volumes:
      - ./nging-data/mysql/data:/var/lib/mysql/
      - ./nging-data/mysql/conf:/etc/mysql/conf.d/
      - ./nging-data/mysql/run:/var/run/mysqld/
    expose:
      - 3306
    cap_add:
      - SYS_NICE 
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password
    restart: always