version: '3'
services:
  nging:
    container_name: nging
    image: admpub/nging:latest
    expose:
      - 9999
    ports:
      - 7999:9999
    volumes:
      - ./nging-data/nging/data/cache:/home/nging_linux_amd64/data/cache
      - ./nging-data/nging/data/ftpdir:/home/nging_linux_amd64/data/ftpdir
      - ./nging-data/nging/data/logs:/home/nging_linux_amd64/data/logs
      - ./nging-data/nging/data/sm2:/home/nging_linux_amd64/data/sm2
      - ./nging-data/nging/myconfig:/home/nging_linux_amd64/myconfig
      - ./nging-data/nging/public:/home/nging_linux_amd64/public
    command: [ "-p", "9999", "-c", "myconfig/config.yaml" ]
    restart: always
